openapi: 3.0.3
info:
  title: CRUD
  version: 1.0.0
  description: CRUD API
paths:
  /:
    get:
      operationId: root_retrieve
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/add/:
    post:
      operationId: add_create
      tags:
      - add
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/delete-exact-match/{name}/:
    delete:
      operationId: delete_exact_match_destroy
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - delete-exact-match
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/delete-partial-match/{name}/:
    delete:
      operationId: delete_partial_match_destroy
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - delete-partial-match
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/list/:
    get:
      operationId: list_retrieve
      tags:
      - list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/search/{name}/:
    get:
      operationId: search_retrieve
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - search
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
