# Generated by Django 5.0.1 on 2024-01-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
